#include "instruction_table.h"
#include "operations.h"
#include "addressing.h"

#define ARRSIZE(a) (sizeof(a) / sizeof(a[0]))

const instruction_t instructions[] = {
    { .operation = &BRK, .opcode = 0x00, .mnemonic = "BRK", .len = 1, .cycles = 0, .addressing = &Implied },  
    { .operation = &ORA, .opcode = 0x01, .mnemonic = "ORA", .len = 2, .cycles = 6, .addressing = &IndirectX },
    { .operation = &ORA, .opcode = 0x05, .mnemonic = "ORA", .len = 2, .cycles = 3, .addressing = &ZeroPage }, 
    { .operation = &ORA, .opcode = 0x09, .mnemonic = "ORA", .len = 2, .cycles = 2, .addressing = &Immediate },
    { .operation = &ORA, .opcode = 0x0D, .mnemonic = "ORA", .len = 3, .cycles = 4, .addressing = &Absolute }, 
    { .operation = &ORA, .opcode = 0x11, .mnemonic = "ORA", .len = 2, .cycles = 5, .addressing = &IndirectY },
    { .operation = &ORA, .opcode = 0x15, .mnemonic = "ORA", .len = 2, .cycles = 4, .addressing = &ZeroPageX },
    { .operation = &ORA, .opcode = 0x19, .mnemonic = "ORA", .len = 3, .cycles = 4, .addressing = &AbsoluteY },
    { .operation = &ORA, .opcode = 0x1D, .mnemonic = "ORA", .len = 3, .cycles = 4, .addressing = &AbsoluteX },
    { .operation = &AND, .opcode = 0x21, .mnemonic = "AND", .len = 2, .cycles = 6, .addressing = &IndirectX },
    { .operation = &AND, .opcode = 0x25, .mnemonic = "AND", .len = 2, .cycles = 3, .addressing = &ZeroPage }, 
    { .operation = &AND, .opcode = 0x29, .mnemonic = "AND", .len = 2, .cycles = 2, .addressing = &Immediate },
    { .operation = &AND, .opcode = 0x2D, .mnemonic = "AND", .len = 3, .cycles = 4, .addressing = &Absolute }, 
    { .operation = &AND, .opcode = 0x31, .mnemonic = "AND", .len = 2, .cycles = 5, .addressing = &IndirectY },
    { .operation = &AND, .opcode = 0x35, .mnemonic = "AND", .len = 2, .cycles = 4, .addressing = &ZeroPageX },
    { .operation = &AND, .opcode = 0x39, .mnemonic = "AND", .len = 3, .cycles = 4, .addressing = &AbsoluteY },
    { .operation = &AND, .opcode = 0x3D, .mnemonic = "AND", .len = 3, .cycles = 4, .addressing = &AbsoluteX },
    { .operation = &EOR, .opcode = 0x41, .mnemonic = "EOR", .len = 2, .cycles = 6, .addressing = &IndirectX },
    { .operation = &EOR, .opcode = 0x45, .mnemonic = "EOR", .len = 2, .cycles = 3, .addressing = &ZeroPage }, 
    { .operation = &EOR, .opcode = 0x49, .mnemonic = "EOR", .len = 2, .cycles = 2, .addressing = &Immediate },
    { .operation = &EOR, .opcode = 0x4D, .mnemonic = "EOR", .len = 3, .cycles = 4, .addressing = &Absolute }, 
    { .operation = &EOR, .opcode = 0x51, .mnemonic = "EOR", .len = 2, .cycles = 5, .addressing = &IndirectY },
    { .operation = &EOR, .opcode = 0x55, .mnemonic = "EOR", .len = 2, .cycles = 4, .addressing = &ZeroPageX },
    { .operation = &EOR, .opcode = 0x59, .mnemonic = "EOR", .len = 3, .cycles = 4, .addressing = &AbsoluteY },
    { .operation = &EOR, .opcode = 0x5D, .mnemonic = "EOR", .len = 3, .cycles = 4, .addressing = &AbsoluteX },
    { .operation = &ADC, .opcode = 0x61, .mnemonic = "ADC", .len = 2, .cycles = 6, .addressing = &IndirectX },
    { .operation = &ADC, .opcode = 0x65, .mnemonic = "ADC", .len = 2, .cycles = 3, .addressing = &ZeroPage },  
    { .operation = &ADC, .opcode = 0x69, .mnemonic = "ADC", .len = 2, .cycles = 2, .addressing = &Immediate }, 
    { .operation = &ADC, .opcode = 0x6D, .mnemonic = "ADC", .len = 3, .cycles = 4, .addressing = &Absolute },  
    { .operation = &ADC, .opcode = 0x71, .mnemonic = "ADC", .len = 2, .cycles = 5, .addressing = &IndirectY }, 
    { .operation = &ADC, .opcode = 0x75, .mnemonic = "ADC", .len = 2, .cycles = 4, .addressing = &ZeroPageX }, 
    { .operation = &ADC, .opcode = 0x79, .mnemonic = "ADC", .len = 3, .cycles = 4, .addressing = &AbsoluteY }, 
    { .operation = &ADC, .opcode = 0x7D, .mnemonic = "ADC", .len = 3, .cycles = 4, .addressing = &AbsoluteX }, 
    { .operation = &LDA, .opcode = 0xA1, .mnemonic = "LDA", .len = 2, .cycles =  6, .addressing = &IndirectX },
    { .operation = &LDA, .opcode = 0xA5, .mnemonic = "LDA", .len = 2, .cycles =  3, .addressing = &ZeroPage }, 
    { .operation = &LDA, .opcode = 0xA9, .mnemonic = "LDA", .len = 2, .cycles =  2, .addressing = &Immediate },
    { .operation = &LDA, .opcode = 0xAD, .mnemonic = "LDA", .len = 3, .cycles =  4, .addressing = &Absolute }, 
    { .operation = &LDA, .opcode = 0xB1, .mnemonic = "LDA", .len = 2, .cycles =  5, .addressing = &IndirectY },
    { .operation = &LDA, .opcode = 0xB5, .mnemonic = "LDA", .len = 2, .cycles =  4, .addressing = &ZeroPageX },
    { .operation = &LDA, .opcode = 0xB9, .mnemonic = "LDA", .len = 3, .cycles =  4, .addressing = &AbsoluteY },
    { .operation = &LDA, .opcode = 0xBD, .mnemonic = "LDA", .len = 3, .cycles =  4, .addressing = &AbsoluteX },
    { .operation = &CMP, .opcode = 0xC1, .mnemonic = "CMP", .len = 2, .cycles = 6, .addressing = &IndirectX }, 
    { .operation = &CMP, .opcode = 0xC5, .mnemonic = "CMP", .len = 2, .cycles = 3, .addressing = &ZeroPage },  
    { .operation = &CMP, .opcode = 0xC9, .mnemonic = "CMP", .len = 2, .cycles = 2, .addressing = &Immediate }, 
    { .operation = &CMP, .opcode = 0xCD, .mnemonic = "CMP", .len = 3, .cycles = 4, .addressing = &Absolute },  
    { .operation = &CMP, .opcode = 0xD1, .mnemonic = "CMP", .len = 2, .cycles = 5, .addressing = &IndirectY }, 
    { .operation = &CMP, .opcode = 0xD5, .mnemonic = "CMP", .len = 2, .cycles = 4, .addressing = &ZeroPageX }, 
    { .operation = &CMP, .opcode = 0xD9, .mnemonic = "CMP", .len = 3, .cycles = 4, .addressing = &AbsoluteY }, 
    { .operation = &CMP, .opcode = 0xDD, .mnemonic = "CMP", .len = 3, .cycles = 4, .addressing = &AbsoluteX }, 
    { .operation = &SBC, .opcode = 0xE1, .mnemonic = "SBC", .len = 2, .cycles = 6, .addressing = &IndirectX }, 
    { .operation = &SBC, .opcode = 0xE5, .mnemonic = "SBC", .len = 2, .cycles = 3, .addressing = &ZeroPage },  
    { .operation = &SBC, .opcode = 0xE9, .mnemonic = "SBC", .len = 2, .cycles = 2, .addressing = &Immediate }, 
    { .operation = &SBC, .opcode = 0xED, .mnemonic = "SBC", .len = 3, .cycles = 4, .addressing = &Absolute },  
    { .operation = &SBC, .opcode = 0xF1, .mnemonic = "SBC", .len = 2, .cycles = 5, .addressing = &IndirectY }, 
    { .operation = &SBC, .opcode = 0xF5, .mnemonic = "SBC", .len = 2, .cycles = 4, .addressing = &ZeroPageX }, 
    { .operation = &SBC, .opcode = 0xF9, .mnemonic = "SBC", .len = 3, .cycles = 4, .addressing = &AbsoluteY }, 
    { .operation = &SBC, .opcode = 0xFD, .mnemonic = "SBC", .len = 3, .cycles = 4, .addressing = &AbsoluteX }, 
    { .operation = &CPX, .opcode = 0xE0, .mnemonic = "CPX", .len = 2, .cycles = 2, .addressing = &Immediate }, 
    { .operation = &CPX, .opcode = 0xE4, .mnemonic = "CPX", .len = 2, .cycles = 3, .addressing = &ZeroPage },  
    { .operation = &CPX, .opcode = 0xEC, .mnemonic = "CPX", .len = 3, .cycles = 4, .addressing = &Absolute },  
    { .operation = &CPY, .opcode = 0xC0, .mnemonic = "CPY", .len = 2, .cycles = 2, .addressing = &Immediate }, 
    { .operation = &CPY, .opcode = 0xC4, .mnemonic = "CPY", .len = 2, .cycles = 3, .addressing = &ZeroPage },  
    { .operation = &CPY, .opcode = 0xCC, .mnemonic = "CPY", .len = 3, .cycles = 4, .addressing = &Absolute },  
    { .operation = &DEC, .opcode = 0xC6, .mnemonic = "DEC", .len = 2, .cycles = 5, .addressing = &ZeroPage },  
    { .operation = &DEC, .opcode = 0xD6, .mnemonic = "DEC", .len = 2, .cycles = 6, .addressing = &ZeroPageX }, 
    { .operation = &DEC, .opcode = 0xCE, .mnemonic = "DEC", .len = 3, .cycles = 6, .addressing = &Absolute },  
    { .operation = &DEC, .opcode = 0xDE, .mnemonic = "DEC", .len = 3, .cycles = 7, .addressing = &AbsoluteX }, 
    { .operation = &INC, .opcode = 0xE6, .mnemonic = "INC", .len = 2, .cycles = 5, .addressing = &ZeroPage },  
    { .operation = &INC, .opcode = 0xF6, .mnemonic = "INC", .len = 2, .cycles = 6, .addressing = &ZeroPageX }, 
    { .operation = &INC, .opcode = 0xEE, .mnemonic = "INC", .len = 3, .cycles = 6, .addressing = &Absolute },  
    { .operation = &INC, .opcode = 0xFE, .mnemonic = "INC", .len = 3, .cycles = 7, .addressing = &AbsoluteX }, 
    { .operation = &DEX, .opcode = 0xCA, .mnemonic = "DEX", .len = 1, .cycles = 2, .addressing = &Implied },
    { .operation = &DEY, .opcode = 0x88, .mnemonic = "DEY", .len = 1, .cycles = 2, .addressing = &Implied },
    { .operation = &INX, .opcode = 0xE8, .mnemonic = "INX", .len = 1, .cycles = 2, .addressing = &Implied },
    { .operation = &INY, .opcode = 0xC8, .mnemonic = "INY", .len = 1, .cycles = 2, .addressing = &Implied },
    { .operation = &ASL, .opcode = 0x0A, .mnemonic = "ASL", .len = 1, .cycles = 2, .addressing = &Accumulator },
    { .operation = &ASL, .opcode = 0x06, .mnemonic = "ASL", .len = 2, .cycles = 5, .addressing = &ZeroPage },  
    { .operation = &ASL, .opcode = 0x16, .mnemonic = "ASL", .len = 2, .cycles = 6, .addressing = &ZeroPageX }, 
    { .operation = &ASL, .opcode = 0x0E, .mnemonic = "ASL", .len = 3, .cycles = 6, .addressing = &Absolute },  
    { .operation = &ASL, .opcode = 0x1E, .mnemonic = "ASL", .len = 3, .cycles = 7, .addressing = &AbsoluteX }, 
    { .operation = &ROL, .opcode = 0x2A, .mnemonic = "ROL", .len = 1, .cycles = 2, .addressing = &Accumulator },   
    { .operation = &ROL, .opcode = 0x26, .mnemonic = "ROL", .len = 2, .cycles = 5, .addressing = &ZeroPage },  
    { .operation = &ROL, .opcode = 0x36, .mnemonic = "ROL", .len = 2, .cycles = 6, .addressing = &ZeroPageX }, 
    { .operation = &ROL, .opcode = 0x2E, .mnemonic = "ROL", .len = 3, .cycles = 6, .addressing = &Absolute },  
    { .operation = &ROL, .opcode = 0x3E, .mnemonic = "ROL", .len = 3, .cycles = 7, .addressing = &AbsoluteX }, 
    { .operation = &LSR, .opcode = 0x4A, .mnemonic = "LSR", .len = 1, .cycles = 2, .addressing = &Accumulator },
    { .operation = &LSR, .opcode = 0x46, .mnemonic = "LSR", .len = 2, .cycles = 5, .addressing = &ZeroPage }, 
    { .operation = &LSR, .opcode = 0x56, .mnemonic = "LSR", .len = 2, .cycles = 6, .addressing = &ZeroPageX },
    { .operation = &LSR, .opcode = 0x4E, .mnemonic = "LSR", .len = 3, .cycles = 6, .addressing = &Absolute }, 
    { .operation = &LSR, .opcode = 0x5E, .mnemonic = "LSR", .len = 3, .cycles = 7, .addressing = &AbsoluteX },
    { .operation = &ROR, .opcode = 0x6A, .mnemonic = "ROR", .len = 1, .cycles = 2, .addressing = &Accumulator },  
    { .operation = &ROR, .opcode = 0x66, .mnemonic = "ROR", .len = 2, .cycles = 5, .addressing = &ZeroPage }, 
    { .operation = &ROR, .opcode = 0x76, .mnemonic = "ROR", .len = 2, .cycles = 6, .addressing = &ZeroPageX },
    { .operation = &ROR, .opcode = 0x6E, .mnemonic = "ROR", .len = 3, .cycles = 6, .addressing = &Absolute }, 
    { .operation = &ROR, .opcode = 0x7E, .mnemonic = "ROR", .len = 3, .cycles = 7, .addressing = &AbsoluteX },
    { .operation = &STA, .opcode = 0x85, .mnemonic = "STA", .len = 2, .cycles = 3, .addressing = &ZeroPage }, 
    { .operation = &STA, .opcode = 0x95, .mnemonic = "STA", .len = 2, .cycles = 4, .addressing = &ZeroPageX },
    { .operation = &STA, .opcode = 0x8D, .mnemonic = "STA", .len = 3, .cycles = 4, .addressing = &Absolute }, 
    { .operation = &STA, .opcode = 0x9D, .mnemonic = "STA", .len = 3, .cycles = 5, .addressing = &AbsoluteX },
    { .operation = &STA, .opcode = 0x99, .mnemonic = "STA", .len = 3, .cycles = 5, .addressing = &AbsoluteY },
    { .operation = &STA, .opcode = 0x81, .mnemonic = "STA", .len = 2, .cycles = 6, .addressing = &IndirectX },
    { .operation = &STA, .opcode = 0x91, .mnemonic = "STA", .len = 2, .cycles = 6, .addressing = &IndirectY },
    { .operation = &LDX, .opcode = 0xA2, .mnemonic = "LDX", .len = 2, .cycles = 2, .addressing = &Immediate },
    { .operation = &LDX, .opcode = 0xA6, .mnemonic = "LDX", .len = 2, .cycles = 3, .addressing = &ZeroPage }, 
    { .operation = &LDX, .opcode = 0xB6, .mnemonic = "LDX", .len = 2, .cycles = 4, .addressing = &ZeroPageY },
    { .operation = &LDX, .opcode = 0xAE, .mnemonic = "LDX", .len = 3, .cycles = 4, .addressing = &Absolute }, 
    { .operation = &LDX, .opcode = 0xBE, .mnemonic = "LDX", .len = 3, .cycles = 4, .addressing = &AbsoluteY },
    { .operation = &LDY, .opcode = 0xA0, .mnemonic = "LDY", .len = 2, .cycles = 2, .addressing = &Immediate },
    { .operation = &LDY, .opcode = 0xA4, .mnemonic = "LDY", .len = 2, .cycles = 3, .addressing = &ZeroPage }, 
    { .operation = &LDY, .opcode = 0xB4, .mnemonic = "LDY", .len = 2, .cycles = 4, .addressing = &ZeroPageX },
    { .operation = &LDY, .opcode = 0xAC, .mnemonic = "LDY", .len = 3, .cycles = 4, .addressing = &Absolute }, 
    { .operation = &LDY, .opcode = 0xBC, .mnemonic = "LDY", .len = 3, .cycles = 4, .addressing = &AbsoluteX },
    { .operation = &STX, .opcode = 0x86, .mnemonic = "STX", .len = 2, .cycles = 3, .addressing = &ZeroPage }, 
    { .operation = &STX, .opcode = 0x96, .mnemonic = "STX", .len = 2, .cycles = 4, .addressing = &ZeroPageY },
    { .operation = &STX, .opcode = 0x8E, .mnemonic = "STX", .len = 3, .cycles = 4, .addressing = &Absolute }, 
    { .operation = &STY, .opcode = 0x84, .mnemonic = "STY", .len = 2, .cycles = 3, .addressing = &ZeroPage }, 
    { .operation = &STY, .opcode = 0x94, .mnemonic = "STY", .len = 2, .cycles = 4, .addressing = &ZeroPageX },
    { .operation = &STY, .opcode = 0x8C, .mnemonic = "STY", .len = 3, .cycles = 4, .addressing = &Absolute }, 
    { .operation = &TAX, .opcode = 0xAA, .mnemonic = "TAX", .len = 1, .cycles = 2, .addressing = &Implied },  
    { .operation = &TXA, .opcode = 0x8A, .mnemonic = "TXA", .len = 1, .cycles = 2, .addressing = &Implied },  
    { .operation = &TAY, .opcode = 0xA8, .mnemonic = "TAY", .len = 1, .cycles = 2, .addressing = &Implied },  
    { .operation = &TYA, .opcode = 0x98, .mnemonic = "TYA", .len = 1, .cycles = 2, .addressing = &Implied },  
    { .operation = &TSX, .opcode = 0xBA, .mnemonic = "TSX", .len = 1, .cycles = 2, .addressing = &Implied },  
    { .operation = &TXS, .opcode = 0x9A, .mnemonic = "TXS", .len = 1, .cycles = 2, .addressing = &Implied },  
    { .operation = &PLA, .opcode = 0x68, .mnemonic = "PLA", .len = 1, .cycles = 4, .addressing = &Implied },  
    { .operation = &PHA, .opcode = 0x48, .mnemonic = "PHA", .len = 1, .cycles = 3, .addressing = &Implied },  
    { .operation = &PLP, .opcode = 0x28, .mnemonic = "PLP", .len = 1, .cycles = 4, .addressing = &Implied },  
    { .operation = &PHP, .opcode = 0x08, .mnemonic = "PHP", .len = 1, .cycles = 3, .addressing = &Implied },  
    { .operation = &BPL, .opcode = 0x10, .mnemonic = "BPL", .len = 2, .cycles = 2, .addressing = &Relative }, 
    { .operation = &BMI, .opcode = 0x30, .mnemonic = "BMI", .len = 2, .cycles = 2, .addressing = &Relative }, 
    { .operation = &BVC, .opcode = 0x50, .mnemonic = "BVC", .len = 2, .cycles = 2, .addressing = &Relative }, 
    { .operation = &BVS, .opcode = 0x70, .mnemonic = "BVS", .len = 2, .cycles = 2, .addressing = &Relative }, 
    { .operation = &BCC, .opcode = 0x90, .mnemonic = "BCC", .len = 2, .cycles = 2, .addressing = &Relative }, 
    { .operation = &BCS, .opcode = 0xB0, .mnemonic = "BCS", .len = 2, .cycles = 2, .addressing = &Relative }, 
    { .operation = &BNE, .opcode = 0xD0, .mnemonic = "BNE", .len = 2, .cycles = 2, .addressing = &Relative }, 
    { .operation = &BEQ, .opcode = 0xF0, .mnemonic = "BEQ", .len = 2, .cycles = 2, .addressing = &Relative }, 
    { .operation = &BRK, .opcode = 0x00, .mnemonic = "BRK", .len = 1, .cycles = 7, .addressing = &Implied },  
    { .operation = &RTI, .opcode = 0x40, .mnemonic = "RTI", .len = 1, .cycles = 6, .addressing = &Implied },  
    { .operation = &JSR, .opcode = 0x20, .mnemonic = "JSR", .len = 3, .cycles = 6, .addressing = &Absolute }, 
    { .operation = &RTS, .opcode = 0x60, .mnemonic = "RTS", .len = 1, .cycles = 6, .addressing = &Implied },  
    { .operation = &JMP, .opcode = 0x4C, .mnemonic = "JMP", .len = 3, .cycles = 3, .addressing = &Absolute }, 
    { .operation = &JMP, .opcode = 0x6C, .mnemonic = "JMP", .len = 3, .cycles = 5, .addressing = &Indirect }, 
    { .operation = &BIT, .opcode = 0x24, .mnemonic = "BIT", .len = 2, .cycles = 3, .addressing = &ZeroPage }, 
    { .operation = &BIT, .opcode = 0x2C, .mnemonic = "BIT", .len = 3, .cycles = 4, .addressing = &Absolute }, 
    { .operation = &CLC, .opcode = 0x18, .mnemonic = "CLC", .len = 1, .cycles = 2, .addressing = &Implied },
    { .operation = &SEC, .opcode = 0x38, .mnemonic = "SEC", .len = 1, .cycles = 2, .addressing = &Implied },
    { .operation = &CLD, .opcode = 0xD8, .mnemonic = "CLD", .len = 1, .cycles = 2, .addressing = &Implied },
    { .operation = &SED, .opcode = 0xF8, .mnemonic = "SED", .len = 1, .cycles = 2, .addressing = &Implied },
    { .operation = &CLI, .opcode = 0x58, .mnemonic = "CLI", .len = 1, .cycles = 2, .addressing = &Implied },
    { .operation = &SEI, .opcode = 0x78, .mnemonic = "SEI", .len = 1, .cycles = 2, .addressing = &Implied },
    { .operation = &CLV, .opcode = 0xB8, .mnemonic = "CLV", .len = 1, .cycles = 2, .addressing = &Implied },
    { .operation = &NOP, .opcode = 0xEA, .mnemonic = "NOP", .len = 1, .cycles = 2, .addressing = &Implied },
    
    { .operation = &ILL, .opcode = 0x04, .mnemonic = "ILL", .len = 2, .cycles = 2, .addressing = &Implied },
    { .operation = &ILL, .opcode = 0x14, .mnemonic = "ILL", .len = 2, .cycles = 2, .addressing = &Implied },
    { .operation = &ILL, .opcode = 0x34, .mnemonic = "ILL", .len = 2, .cycles = 2, .addressing = &Implied },
    { .operation = &ILL, .opcode = 0x44, .mnemonic = "ILL", .len = 2, .cycles = 2, .addressing = &Implied },
    { .operation = &ILL, .opcode = 0x54, .mnemonic = "ILL", .len = 2, .cycles = 2, .addressing = &Implied },
    { .operation = &ILL, .opcode = 0x64, .mnemonic = "ILL", .len = 2, .cycles = 2, .addressing = &Implied },
    { .operation = &ILL, .opcode = 0x74, .mnemonic = "ILL", .len = 2, .cycles = 2, .addressing = &Implied },
    { .operation = &ILL, .opcode = 0xD4, .mnemonic = "ILL", .len = 2, .cycles = 2, .addressing = &Implied },
    { .operation = &ILL, .opcode = 0xF4, .mnemonic = "ILL", .len = 2, .cycles = 2, .addressing = &Implied },

    { .operation = &ILL, .opcode = 0x80, .mnemonic = "ILL", .len = 2, .cycles = 2, .addressing = &Implied },
    
    { .operation = &LAX, .opcode = 0xA3, .mnemonic = "LAX", .len = 2, .cycles = 6, .addressing = &IndirectX },
    { .operation = &LAX, .opcode = 0xA7, .mnemonic = "LAX", .len = 2, .cycles = 3, .addressing = &ZeroPage },
    { .operation = &LAX, .opcode = 0xAF, .mnemonic = "LAX", .len = 3, .cycles = 4, .addressing = &Absolute },
    { .operation = &LAX, .opcode = 0xB3, .mnemonic = "LAX", .len = 2, .cycles = 5, .addressing = &IndirectY },
    { .operation = &LAX, .opcode = 0xB7, .mnemonic = "LAX", .len = 2, .cycles = 4, .addressing = &ZeroPageY },
    { .operation = &LAX, .opcode = 0xBF, .mnemonic = "LAX", .len = 3, .cycles = 4, .addressing = &AbsoluteY },

    { .operation = &SAX, .opcode = 0x83, .mnemonic = "SAX", .len = 2, .cycles = 6, .addressing = &IndirectX },
    { .operation = &SAX, .opcode = 0x87, .mnemonic = "SAX", .len = 2, .cycles = 3, .addressing = &ZeroPage },
    { .operation = &SAX, .opcode = 0x8F, .mnemonic = "SAX", .len = 3, .cycles = 4, .addressing = &Absolute },
    { .operation = &SAX, .opcode = 0x97, .mnemonic = "SAX", .len = 2, .cycles = 4, .addressing = &ZeroPageY },

    { .operation = &iSBC, .opcode = 0xEB, .mnemonic = "iSBC", .len = 2, .cycles = 2, .addressing = &Immediate },

    { .operation = &DCP, .opcode = 0xC3, .mnemonic = "DCP", .len = 2, .cycles = 8, .addressing = &IndirectX },
    { .operation = &DCP, .opcode = 0xC7, .mnemonic = "DCP", .len = 2, .cycles = 5, .addressing = &ZeroPage },
    { .operation = &DCP, .opcode = 0xCF, .mnemonic = "DCP", .len = 3, .cycles = 6, .addressing = &IndirectX },
    { .operation = &DCP, .opcode = 0xD3, .mnemonic = "DCP", .len = 2, .cycles = 8, .addressing = &IndirectX },
    { .operation = &DCP, .opcode = 0xD7, .mnemonic = "DCP", .len = 2, .cycles = 6, .addressing = &ZeroPage },
    { .operation = &DCP, .opcode = 0xDB, .mnemonic = "DCP", .len = 3, .cycles = 7, .addressing = &Absolute },
    { .operation = &DCP, .opcode = 0xDF, .mnemonic = "DCP", .len = 3, .cycles = 7, .addressing = &Absolute },

    { .operation = &NOP, .opcode = 0x1A, .mnemonic = "iNOP", .len = 1, .cycles = 2, .addressing = &Implied },
    { .operation = &NOP, .opcode = 0x3A, .mnemonic = "iNOP", .len = 1, .cycles = 2, .addressing = &Implied },
    { .operation = &NOP, .opcode = 0x5A, .mnemonic = "iNOP", .len = 1, .cycles = 2, .addressing = &Implied },
    { .operation = &NOP, .opcode = 0x7A, .mnemonic = "iNOP", .len = 1, .cycles = 2, .addressing = &Implied },
    { .operation = &NOP, .opcode = 0xDA, .mnemonic = "iNOP", .len = 1, .cycles = 2, .addressing = &Implied },
    { .operation = &NOP, .opcode = 0xFA, .mnemonic = "iNOP", .len = 1, .cycles = 2, .addressing = &Implied },

    { .operation = &ILL, .opcode = 0x0C, .mnemonic = "ILL", .len = 3, .cycles = 2, .addressing = &Implied },
    { .operation = &ILL, .opcode = 0x1C, .mnemonic = "ILL", .len = 3, .cycles = 2, .addressing = &Implied },
    { .operation = &ILL, .opcode = 0x3C, .mnemonic = "ILL", .len = 3, .cycles = 2, .addressing = &Implied },
    { .operation = &ILL, .opcode = 0x5C, .mnemonic = "ILL", .len = 3, .cycles = 2, .addressing = &Implied },
    { .operation = &ILL, .opcode = 0x7C, .mnemonic = "ILL", .len = 3, .cycles = 2, .addressing = &Implied },
    { .operation = &ILL, .opcode = 0xDC, .mnemonic = "ILL", .len = 3, .cycles = 2, .addressing = &Implied },
    { .operation = &ILL, .opcode = 0xFC, .mnemonic = "ILL", .len = 3, .cycles = 2, .addressing = &Implied },

    { .operation = &END, .opcode = 0xFF, .mnemonic = "END", .len = 1, .cycles = 1, .addressing = &Implied },
};

instruction_t instructions_sorted[256] = { 0 };

void initialize_instructions_sorted(void) {
    for (int i = 0; i < ARRSIZE(instructions); i++) {
        instructions_sorted[instructions[i].opcode] = instructions[i];
    }
}

const instruction_t *get_instruction(uint8_t opcode) {
    return &instructions_sorted[opcode];
}
